config:
  author: Kunal Shah
  siteName: Welcome
  siteDescription: The personal blog of Kunal Shah
  defaultPageTitle: Kunal Shah
  blogTitle: Kunal's Blog
  baseUrl: https://kunal.sh

  # For Twitter cards, this logo must be a hosted url, not a relative path.
  # Must be square. Minimum size is 144x144; maximum size 4096x4096.
  websiteLogo: "https://cdn.auth0.com/blog/logos/nextjs-logo.png"

  # if your string begins with a special character, you usually have to put it in quotes
  twitterHandle: "@kunalsh22"
  twitterCardType: Kunal Shah on Twitter

  # This is list is used to create the links in the navigation panel
  navigation:
    - { text: Home, link: / }
    - { text: Blog, link: /blog }
    - { text: Links, link: /links }
    - { text: Projects, link: /projects }

    - { text: "Tech Stack", link: /tech-stack }

  css:
    primaryColor: "#536DFE"
    accentColor: "#555"
    lightGray: "#eeeeee"
    backgroundColor: "#ffffff"
    black: "#333"
